### ISSUE TITLE
华为P20Pro上面运行，点击返回到时候经常闪退。

### ISSUE THREAD

**Issue by liusong001** [ForgetSky/ForgetSkyWanAndroid#2]

**Comment by ForgetSky** [comment]
方便提供一下详细的错误日志吗

**Comment by ForgetSky** [comment]
使用的是否是最新代码？昨天修复了一个关于返回的问题

**Comment by liusong001** [comment]
我是扫到二维码安装的，这是我看到的日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
        at com.forgetsky.wanandroid.utils.CommonUtils.hideKeyBoard(CommonUtils.java:93)
        at com.forgetsky.wanandroid.base.activity.BaseActivity.onBackPressedSupport(BaseActivity.java:72)
        at com.forgetsky.wanandroid.modules.main.ui.activity.CommonActivity.lambda$initToolbar$0(CommonActivity.java:94)
        at com.forgetsky.wanandroid.modules.main.ui.activity.-$$Lambda$CommonActivity$j_P4u9GZxao-qgYiJ-Yjmewh8t4.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6652)
        at android.view.View.performClickInternal(View.java:6624)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26213)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by liusong001** [comment]
刚刚用最新代码跑了一下，没有问题了。

**Comment by ForgetSky** [comment]
现在二维码下载也更新了最新的apk
